apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: prometheus-deployment
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prometheus-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: prometheus-deployment
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus/"
        - "--web.enable-lifecycle"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
      - name: prometheus-config-volume
        configMap:
          defaultMode: 420
          name: prometheus-server-conf
      - name: prometheus-storage-volume
        emptyDir: {}
