apiVersion: v1
kind: Pod
metadata:
  name: my-arg2-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx
    command:
      - nginx # run a simple echo command when container is fired up. This will output nothing
    args:
      - -g
      - daemon off;
      - -q