apiVersion: v1
kind: Pod
metadata:
  name: my-arg-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx
    command: ['nginx']  # run the 'nginx' command when container is started.
    args: ['-g', 'daemon off;', '-q'] # the arguments (-g daemon off; -q) passed into the command. This will silent the nginx logs