apiVersion: v1
kind: Pod
metadata:
  name: my-command-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['echo hello']  # run a simple echo command when container is fired up
  restartPolicy: Never  # do not attempt to restart the container when command is finished