apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:  # probe block
      httpGet:  # any http response over 200 and below 400 is a success
        path: /healthz  # path for check on the pod
        port: 8080  # tcp port to use
        httpHeaders:  # custom http header block
        - name: Custom-Header  # name of custom header
          value: Awesome  # value to send in custom header
      initialDelaySeconds: 3  # delay before first probe
      periodSeconds: 3  # interval of probes

# For the first 10 seconds that the Container is alive, the /healthz handler returns a status of 200. After that, the handler returns a status of 500.
# The kubelet starts performing health checks 3 seconds after the Container starts. So the first couple of health checks will succeed. But after 10 seconds, the health checks will fail, and the kubelet will kill and restart the Container.