apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:  # command style probe.
        command:  # if exit code is 0 command is successful. Anything else is fail.
        - cat  # execute cat command
        - /tmp/healthy  # cat this file
      initialDelaySeconds: 5  # wait before first probe
      periodSeconds: 5  # interval for probes

# For the first 30 seconds of the Container’s life, there is a /tmp/healthy file. So during the first 30 seconds, the command cat /tmp/healthy returns a success code. After 30 seconds, cat /tmp/healthy returns a failure code