apiVersion: v1
kind: Pod
metadata:
  name: my-port-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx  # has a built in always-run command
    ports:  # utilised to expose this container
      - containerPort: 80  # export port 80 to things outside this pod