apiVersion: v1
kind: Pod
metadata:
  name: my-resource-pod
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo Hello kubernetes! && sleep 3600']
      resources:  # fields for resources
        requests:  # minimum required resources for worker node to take on the pod
          memory: "64Mi" # 64 Mebibytes (mega + binary = mebi)
          cpu: "250m"  # 250 milliCPUs, i.e. 0.25 CPU cores
        limits:  # maximum resources used by the container, if more is used, probably kill it.
          memory: "128Mi"  # 128 Mebibytes
          cpu: "500m"  # 500 milliCPUs, 0.5 CPU cores