apiVersion: v1
kind: Pod
metadata:
  name: my-securitycontext-pod
spec:
  securityContext:  # fields for securityContext
    runAsUser: 2000  # run as this user id (defined by worker nodes OS!)
    fsGroup: 3000  # run as this group (defined by worker nodes OS!)
  containers:  # fields for containers
    - name: myapp-container
      image: busybox  # just a normal busybox container
      command: ['sh', '-c', "cat /message/message.txt && sleep 3600"]  # sh -c cat /message/message.txt && sleep 3600
      volumeMounts:  # fields for mounting volumes to container
        - name: message-volume  # name of the volume we are mounting
          mountPath: /message  # mounts to /message on the container
  volumes:  # fields for volumes
    - name: message-volume  # mountable name for volume
      hostPath:  # specifies that it's on the worker node (Host)
        path: /etc/message  # path on the worker node

#This should be done on your worker nodes
#sudo useradd -u 2000 container-user-0
#sudo groupadd -g 3000 container-group-0
#sudo useradd -u 2001 container-user-1
#sudo groupadd -g 3001 container-group-1
#sudo mkdir -p /etc/message/
#echo "Hello, World!" | sudo tee -a /etc/message/message.txt
#sudo chown 2000:3000 /etc/message/message.txt
#sudo chmod 640 /etc/message/message.txt