# requires a 'kubectl create serviceaccount my-serviceaccount'
apiVersion: v1  # mandatory api version
kind: Pod  # mandatory kind
metadata:  # mandatory metadata block
  name: my-serviceaccount-pod  # Set name for our pod
spec:  # mandatory spec block
  serviceAccountName: my-serviceaccount  # reference to the service account in our cluster
  containers:  # container spec block
    - name: myapp-container  # mandatory name block
      image: busybox  # simple container
      command: ['sh', '-c', "echo Hello, Kubernetes! && sleep 3600"]  # basic run command
