apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "echo Hello, Kubernetes && sleep 3600"]  # simple hello world and stay awake for 1 hour
    env:  # specify environment variables
    - name: MY_PASSWORD  # create a name of the environment variable
      valueFrom:  # grab the value from an external source,
        secretKeyRef:  # refer to a a secret
          name: my-secret  # specifying the secret map's name
          key: myKey  # specify the key-value we want to set for our variable