apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:  # enable volume mounting
    - mountPath: /tmp/storage  # mount volumes to this mount point
      name: my-volume  # mount the volume called "my-volume"
  volumes:  # list of volumes that we declare
  - name: my-volume  # we call this volume
    emptyDir: {}  # we create an emptydirectory type of volume. There are many types of volumes