apiVersion: batch/v1  # jobs are part of the batch api
kind: Job  # mandatory kind
metadata:  # mandatory metadata
  name: pi  # name our job
spec:  # mandatory spec
  template: # Desired state for pods in this job. Much like the deployment template has a desired state for pods (in a template)
    spec:
      containers:
      - name: pi
        image: perl  # run a perl container
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]  # print pi or whatever
      restartPolicy: Never  # never restart, just execute the job once.
  backoffLimit: 4  # how many times it will re-attempt if it would fail.