---
apiVersion: v1
kind: Namespace
metadata:
  name: cron-hpa
  labels:
    app.kubernetes.io/name: cron-hpa
    app.kubernetes.io/instance: cron-hpa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cron-hpa-role
subjects:
- kind: ServiceAccount
  name: cron-hpa-role
  namespace: cron-hpa
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-hpa-role
  namespace: cron-hpa
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-hpa-scale-down
  namespace: cron-hpa
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cron-hpa-role
          containers:
          - name: cron-hpa-scale-down
            image: bitnami/kubectl
            command: [ "/bin/sh", "-c" ]
            args:
              - echo "Patching hpa to minimum 1 replica. This allows for scale down";
                kubectl patch hpa php-apache -p '{"spec":{"minReplicas":1}}'
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-hpa-scale-up
  namespace: cron-hpa
spec:
  schedule: "1/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cron-hpa-role
          containers:
          - name: cron-hpa-scale-up
            image: bitnami/kubectl
            command: [ "/bin/sh", "-c" ]
            args:
              - echo "Patching hpa to minimum 5 replicas. This ensures scale up";
                kubectl patch hpa php-apache -p '{"spec":{"minReplicas":5}}'
          restartPolicy: OnFailure