apiVersion: v1  # mandatory api version
kind: Secret  # Object to store sensitive data
metadata:  # mandatory metadata block
  name: my-secret # name to be referenced in pods/deployments!
data:  # arbitrary data field, requires base64 encoding
  username: YWRtaW4=  # 'admin' encoded with base64
  password: LW0gbXlwYXNzd29yZAo=  # 'mypassword' encoded with base64