apiVersion: v1  # mandatory api version
kind: Secret  # Object to store sensitive data
metadata:  # mandatory metadata block
  name: my-stringdata-secret # name to be referenced in pods/deployments!
stringData:  # write-only convenience block to not have to deal with base64 encoding
  myKey: myPassword  # configure a key-value pair as a simple string
