kind: Pod
apiVersion: v1
metadata:
  name: my-pvc-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:  # Mount volumes to this pod
    - mountPath: "/mnt/storage"  # this is where to mount it to
      name: my-storage  # refer to the storage
  volumes:  # create volumes for this pod
  - name: my-storage  # call volume "my-storage"
    persistentVolumeClaim:  # Use our previously created PVC
      claimName: my-pvc  # use the claim called "my-pvc". Refer to the metadata section of the PVC